# Generated by Django 3.2.5 on 2023-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
