# Generated by Django 3.2.5 on 2023-04-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_attendance', '0002_attendance_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='id_card_number',
            new_name='id_card',
        ),
    ]
