# Generated by Django 3.2.5 on 2023-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_attendance', '0003_auto_20230420_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
