# Generated by Django 3.2.5 on 2023-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_attendance', '0007_attendance_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
