# Generated by Django 3.2.5 on 2023-06-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_attendance', '0008_attendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
