# Generated by Django 3.2.5 on 2023-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='card_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
