# Generated by Django 3.2.5 on 2023-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0003_student_encodings_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
