# Generated by Django 3.2.5 on 2023-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0004_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='card_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='encodings_file',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
