# Generated by Django 3.2.5 on 2023-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0005_auto_20230507_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='card_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
