# Generated by Django 3.2.5 on 2023-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0007_auto_20230508_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
